module.exports = {
  students: [
    {
      id: 1,
      name: "Rehab Doe",
      phone: "123-456-7890",
      email: "john.doe@example.com",
      dateJoined: "2023-01-01",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 2,
      name: "Jane Smith",
      phone: "987-654-3210",
      email: "jane.smith@example.com",
      dateJoined: "2023-02-15",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 3,
      name: "Bob Johnson",
      phone: "555-123-4567",
      email: "bob.johnson@example.com",
      dateJoined: "2023-03-10",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 4,
      name: "rehab",
      phone: "555-333-4567",
      email: "rehab.johnson@example.com",
      dateJoined: "2023-03-11",
      role: "member",
    },
    {
      id: 5,
      name: "Muhammad",
      phone: "511-333-4567",
      email: "muhammad.johnson@example.com",
      dateJoined: "2023-03-12",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 6,
      name: "nada",
      phone: "522-333-4567",
      email: "nada.johnson@example.com",
      dateJoined: "2023-03-13",
      role: "student",
      tags: ["football,supplay ch"],
    },
    {
      id: 7,
      name: "esraa",
      phone: "533-333-4567",
      email: "esraa.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 8,
      name: "ali",
      phone: "533-333-4567",
      email: "ali.johnson@example.com",
      dateJoined: "2023-03-15",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 9,
      name: "omar",
      phone: "533-333-4567",
      email: "omar.johnson@example.com",
      dateJoined: "2023-03-16",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 10,
      name: "safy",
      phone: "533-333-4567",
      email: "safy.johnson@example.com",
      dateJoined: "2023-03-16",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 11,
      name: "lola",
      phone: "533-333-4567",
      email: "lola.johnson@example.com",
      dateJoined: "2023-03-16",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 12,
      name: "zain",
      phone: "533-333-4567",
      email: "zain.johnson@example.com",
      dateJoined: "2023-03-17",
      role: "student",
      tags: ["football,supplay ch"],
    },
    {
      id: 13,
      name: "koky",
      phone: "533-333-4567",
      email: "koky.johnson@example.com",
      dateJoined: "2023-03-18",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 14,
      name: "hassan",
      phone: "533-333-4567",
      email: "hassan.johnson@example.com",
      dateJoined: "2023-03-19",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 15,
      name: "karim",
      phone: "533-333-4567",
      email: "karim.johnson@example.com",
      dateJoined: "2023-03-120",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 18,
      name: "tamara",
      phone: "533-333-4567",
      email: "tamara.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 19,
      name: "ZINAB",
      phone: "533-333-4567",
      email: "zinab.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 20,
      name: "laila",
      phone: "533-333-4567",
      email: "laila.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 21,
      name: "noha",
      phone: "533-333-4567",
      email: "noha.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 22,
      name: "alia",
      phone: "533-333-4567",
      email: "alia.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 23,
      name: "nour",
      phone: "533-333-4567",
      email: "nour.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 24,
      name: "osama",
      phone: "533-333-4567",
      email: "osama.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 25,
      name: "kera",
      phone: "533-333-4567",
      email: "kera.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 26,
      name: "kera",
      phone: "533-333-4567",
      email: "kera.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "student",
      tags: ["football,supplay ch"],
    },
    {
      id: 27,
      name: "zozo",
      phone: "533-333-4567",
      email: "zozo.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 28,
      name: "kadar",
      phone: "533-333-4567",
      email: "kadar.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
    {
      id: 29,
      name: "salma",
      phone: "533-333-4567",
      email: "esraa.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "member",
      tags: ["football,supplay ch"],
    },
    {
      id: 30,
      name: "kamila",
      phone: "533-333-4567",
      email: "kamila.johnson@example.com",
      dateJoined: "2023-03-14",
      role: "Admin",
      tags: ["football,supplay ch"],
    },
  ],
};
